CREATE VIEW strtp_city_ivst AS
    SELECT
        INVESTMENT.INVSTID,
        STARTUP.NAME,
        CITY.CITY,
        CITY.STATE_CODE,
        CITY.COUNTRY_CODE,
        INVESTMENT.SEED,
        INVESTMENT.VENTURE,
        STARTUP.TOTAL_FUNDING
    FROM INVESTMENT
        JOIN STARTUP ON INVESTMENT.NAME = STARTUP.NAME
        JOIN CITY ON STARTUP.CITY = CITY.CITY
    ORDER BY INVESTMENT.INVSTID
;

SELECT * FROM strtp_city_ivst;